/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    categories: Category;
    orders: Order;
    reviews: Review;
    coupons: Coupon;
    tags: Tag;
    media: Media;
    pages: Page;
    posts: Post;
    'customer-tiers': CustomerTier;
    'gift-cards': GiftCard;
    'abandoned-carts': AbandonedCart;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'customer-tiers': CustomerTiersSelect<false> | CustomerTiersSelect<true>;
    'gift-cards': GiftCardsSelect<false> | GiftCardsSelect<true>;
    'abandoned-carts': AbandonedCartsSelect<false> | AbandonedCartsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'top-bar': TopBar;
    'cod-settings': CodSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'top-bar': TopBarSelect<false> | TopBarSelect<true>;
    'cod-settings': CodSettingsSelect<false> | CodSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  avatar?: (string | null) | Media;
  phone?: string | null;
  dateOfBirth?: string | null;
  role?: ('customer' | 'admin' | 'editor') | null;
  customerTier?: (string | null) | CustomerTier;
  lifetimeValue?: number | null;
  totalOrders?: number | null;
  tierUpdatedAt?: string | null;
  isNewsletterSubscriber?: boolean | null;
  addresses?:
    | {
        label?: string | null;
        firstName?: string | null;
        lastName?: string | null;
        line1?: string | null;
        line2?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        country?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  wishlist?: (string | Product)[] | null;
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-tiers".
 */
export interface CustomerTier {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  tierLevel?: number | null;
  color?: string | null;
  isActive?: boolean | null;
  minLifetimeSpend?: number | null;
  minOrdersCount?: number | null;
  minAccountAgeDays?: number | null;
  discountPercent?: number | null;
  freeShipping?: boolean | null;
  earlyAccess?: boolean | null;
  exclusiveProducts?: (string | Product)[] | null;
  birthdayBonus?: {
    enabled?: boolean | null;
    discountPercent?: number | null;
    validDays?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  sku?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  featured?: boolean | null;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: string | Category;
  tags?: (string | Tag)[] | null;
  gender?: ('unisex' | 'men' | 'women' | 'kids') | null;
  brand?: string | null;
  price: number;
  compareAtPrice?: number | null;
  costPerItem?: number | null;
  weight?: number | null;
  dimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  images?: (string | Media)[] | null;
  variants?:
    | {
        sku: string;
        stock?: number | null;
        trackInventory?: boolean | null;
        size?: ('XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'One Size') | null;
        color?: string | null;
        colorHex?: string | null;
        price: number;
        compareAtPrice?: number | null;
        costPerItem?: number | null;
        inventoryLocations?:
          | {
              locationName?: string | null;
              quantity?: number | null;
              id?: string | null;
            }[]
          | null;
        images?: (string | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  inventoryLocations?:
    | {
        locationName: string;
        quantity?: number | null;
        lowStockThreshold?: number | null;
        id?: string | null;
      }[]
    | null;
  currencyPrices?:
    | {
        currency: 'USD' | 'EUR' | 'GBP' | 'CAD' | 'AUD' | 'JPY' | 'INR';
        price: number;
        compareAtPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  metafields?:
    | {
        namespace: string;
        key: string;
        type?: ('string' | 'integer' | 'decimal' | 'boolean' | 'json') | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  material?: string | null;
  careInstructions?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  averageRating?: number | null;
  reviewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  description?: string | null;
  image?: (string | null) | Media;
  parent?: (string | null) | Category;
  order?: number | null;
  featuredOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  slug?: string | null;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber?: string | null;
  customer?: (string | null) | User;
  guestEmail?: string | null;
  currency?: string | null;
  status?: ('pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded' | 'cod_pending' | 'cod_collected') | null;
  paymentMethod?: ('stripe' | 'cod' | 'paypal' | 'bank_transfer') | null;
  items?:
    | {
        product?: (string | null) | Product;
        variantSku?: string | null;
        quantity?: number | null;
        price?: number | null;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  shippingCost?: number | null;
  tax?: number | null;
  discount?: number | null;
  total?: number | null;
  couponCode?: string | null;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  billingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  shippingMethod?: string | null;
  trackingNumber?: string | null;
  notes?: string | null;
  invoiceNumber?: string | null;
  invoiceDate?: string | null;
  invoiceSent?: boolean | null;
  stripePaymentIntentId?: string | null;
  paypalOrderId?: string | null;
  isCOD?: boolean | null;
  codStatus?:
    | ('pending' | 'out_for_delivery' | 'delivery_attempted' | 'delivered' | 'amount_collected' | 'cod_failed')
    | null;
  codAmount?: number | null;
  codCollectedAt?: string | null;
  codCollectedBy?: string | null;
  codDeliveryAttempts?: number | null;
  codDeliveryNotes?: string | null;
  codVerificationCode?: string | null;
  fulfillmentEvents?:
    | {
        status: 'pending' | 'in_transit' | 'delivered' | 'failed' | 'returned';
        location?: string | null;
        timestamp?: string | null;
        message?: string | null;
        trackingNumber?: string | null;
        id?: string | null;
      }[]
    | null;
  shippedFromLocation?: string | null;
  estimatedDeliveryDate?: string | null;
  returns?:
    | {
        returnNumber?: string | null;
        status?: ('requested' | 'approved' | 'received' | 'inspected' | 'refunded' | 'rejected' | 'closed') | null;
        requestedAt?: string | null;
        receivedAt?: string | null;
        refundedAt?: string | null;
        items?:
          | {
              product?: (string | null) | Product;
              variantSku?: string | null;
              quantity?: number | null;
              price?: number | null;
              refundAmount?: number | null;
              returnReason?: ('defective' | 'wrong_item' | 'not_as_described' | 'changed_mind' | 'other') | null;
              customerNotes?: string | null;
              id?: string | null;
            }[]
          | null;
        totalRefundAmount?: number | null;
        restockingFee?: number | null;
        adminNotes?: string | null;
        id?: string | null;
      }[]
    | null;
  returnStatus?: ('none' | 'requested' | 'in_progress' | 'completed') | null;
  isDraft?: boolean | null;
  draftCreatedAt?: string | null;
  draftExpiresAt?: string | null;
  draftInvoiceSent?: boolean | null;
  draftInvoiceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  product: string | Product;
  author: string | User;
  title?: string | null;
  body?: string | null;
  rating: number;
  verified?: boolean | null;
  images?: (string | Media)[] | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  helpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  code: string;
  triggerType?: ('manual' | 'automatic') | null;
  type: 'percentage' | 'fixed' | 'free_shipping' | 'buy_x_get_y';
  value?: number | null;
  minOrderAmount?: number | null;
  minQuantity?: number | null;
  isActive?: boolean | null;
  maxUses?: number | null;
  maxUsesPerCustomer?: number | null;
  usedCount?: number | null;
  validFrom?: string | null;
  validUntil?: string | null;
  buyXGetYRules?:
    | {
        buyQuantity?: number | null;
        buyProduct?: (string | null) | Product;
        getQuantity?: number | null;
        getProduct?: (string | null) | Product;
        getDiscountPercent?: number | null;
        id?: string | null;
      }[]
    | null;
  applicableProducts?: (string | Product)[] | null;
  excludedProducts?: (string | Product)[] | null;
  applicableCategories?: (string | Category)[] | null;
  excludedCategories?: (string | Category)[] | null;
  customerSegments?:
    | ('new_customers' | 'returning_customers' | 'vip' | 'wholesale' | 'newsletter_subscribers')[]
    | null;
  applicableCustomerTiers?: (string | CustomerTier)[] | null;
  specificCustomers?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  status?: ('draft' | 'published' | 'archived') | null;
  layout?:
    | (
        | {
            slides?:
              | {
                  headline: string;
                  subheadline?: string | null;
                  cta?: string | null;
                  link?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            autoplay?: boolean | null;
            autoplayDelay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            categories?:
              | {
                  category: string | Category;
                  overrideImage?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            showViewAll?: boolean | null;
            viewAllText?: string | null;
            viewAllLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredCategories';
          }
        | {
            title: string;
            products: (string | Product)[];
            showGenderFilter?: boolean | null;
            showViewAll?: boolean | null;
            viewAllText?: string | null;
            viewAllLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productRail';
          }
        | {
            sectionLabel?: string | null;
            headline: string;
            description?: string | null;
            image?: (string | null) | Media;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandStory';
          }
        | {
            sectionLabel?: string | null;
            headline?: string | null;
            subheadline?: string | null;
            placeholder?: string | null;
            buttonText?: string | null;
            mobileButtonText?: string | null;
            privacyText?: string | null;
            successHeadline?: string | null;
            successMessage?: string | null;
            trustBadges?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            title?: string | null;
            testimonials?:
              | {
                  author: string;
                  location: string;
                  body: string;
                  rating?: number | null;
                  verified?: boolean | null;
                  date?: string | null;
                  id?: string | null;
                }[]
              | null;
            autoplay?: boolean | null;
            autoplayDelay?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  status?: ('draft' | 'published' | 'archived') | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (string | null) | User;
  publishedAt?: string | null;
  featuredImage?: (string | null) | Media;
  gallery?: (string | Media)[] | null;
  tags?: (string | Tag)[] | null;
  isFeatured?: boolean | null;
  allowComments?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards".
 */
export interface GiftCard {
  id: string;
  code: string;
  status?: ('active' | 'redeemed' | 'expired' | 'disabled') | null;
  initialValue: number;
  balance: number;
  currency?: string | null;
  expiresAt?: string | null;
  createdAt: string;
  recipientName?: string | null;
  recipientEmail?: string | null;
  personalMessage?: string | null;
  sender?: (string | null) | User;
  transactions?:
    | {
        type: 'purchase' | 'redemption' | 'refund' | 'adjustment';
        amount: number;
        date: string;
        order?: (string | null) | Order;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts".
 */
export interface AbandonedCart {
  id: string;
  customer?: (string | null) | User;
  guestEmail?: string | null;
  items?:
    | {
        product?: (string | null) | Product;
        variantSku?: string | null;
        quantity?: number | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  tax?: number | null;
  total?: number | null;
  currency?: string | null;
  abandonedAt?: string | null;
  recoveredAt?: string | null;
  recoveryStatus?: ('pending' | 'email_sent' | 'email_opened' | 'link_clicked' | 'converted' | 'expired') | null;
  order?: (string | null) | Order;
  recoveryEmailSentAt?: string | null;
  discountCode?: string | null;
  recoveryLinkToken?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  referrer?: string | null;
  utmData?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'customer-tiers';
        value: string | CustomerTier;
      } | null)
    | ({
        relationTo: 'gift-cards';
        value: string | GiftCard;
      } | null)
    | ({
        relationTo: 'abandoned-carts';
        value: string | AbandonedCart;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  avatar?: T;
  phone?: T;
  dateOfBirth?: T;
  role?: T;
  customerTier?: T;
  lifetimeValue?: T;
  totalOrders?: T;
  tierUpdatedAt?: T;
  isNewsletterSubscriber?: T;
  addresses?:
    | T
    | {
        label?: T;
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  wishlist?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  status?: T;
  featured?: T;
  shortDescription?: T;
  longDescription?: T;
  category?: T;
  tags?: T;
  gender?: T;
  brand?: T;
  price?: T;
  compareAtPrice?: T;
  costPerItem?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  images?: T;
  variants?:
    | T
    | {
        sku?: T;
        stock?: T;
        trackInventory?: T;
        size?: T;
        color?: T;
        colorHex?: T;
        price?: T;
        compareAtPrice?: T;
        costPerItem?: T;
        inventoryLocations?:
          | T
          | {
              locationName?: T;
              quantity?: T;
              id?: T;
            };
        images?: T;
        id?: T;
      };
  inventoryLocations?:
    | T
    | {
        locationName?: T;
        quantity?: T;
        lowStockThreshold?: T;
        id?: T;
      };
  currencyPrices?:
    | T
    | {
        currency?: T;
        price?: T;
        compareAtPrice?: T;
        id?: T;
      };
  metafields?:
    | T
    | {
        namespace?: T;
        key?: T;
        type?: T;
        value?: T;
        id?: T;
      };
  material?: T;
  careInstructions?: T;
  metaTitle?: T;
  metaDescription?: T;
  averageRating?: T;
  reviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  order?: T;
  featuredOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  guestEmail?: T;
  currency?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        quantity?: T;
        price?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  tax?: T;
  discount?: T;
  total?: T;
  couponCode?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
        phone?: T;
      };
  shippingMethod?: T;
  trackingNumber?: T;
  notes?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  invoiceSent?: T;
  stripePaymentIntentId?: T;
  paypalOrderId?: T;
  isCOD?: T;
  codStatus?: T;
  codAmount?: T;
  codCollectedAt?: T;
  codCollectedBy?: T;
  codDeliveryAttempts?: T;
  codDeliveryNotes?: T;
  codVerificationCode?: T;
  fulfillmentEvents?:
    | T
    | {
        status?: T;
        location?: T;
        timestamp?: T;
        message?: T;
        trackingNumber?: T;
        id?: T;
      };
  shippedFromLocation?: T;
  estimatedDeliveryDate?: T;
  returns?:
    | T
    | {
        returnNumber?: T;
        status?: T;
        requestedAt?: T;
        receivedAt?: T;
        refundedAt?: T;
        items?:
          | T
          | {
              product?: T;
              variantSku?: T;
              quantity?: T;
              price?: T;
              refundAmount?: T;
              returnReason?: T;
              customerNotes?: T;
              id?: T;
            };
        totalRefundAmount?: T;
        restockingFee?: T;
        adminNotes?: T;
        id?: T;
      };
  returnStatus?: T;
  isDraft?: T;
  draftCreatedAt?: T;
  draftExpiresAt?: T;
  draftInvoiceSent?: T;
  draftInvoiceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  author?: T;
  title?: T;
  body?: T;
  rating?: T;
  verified?: T;
  images?: T;
  status?: T;
  helpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  triggerType?: T;
  type?: T;
  value?: T;
  minOrderAmount?: T;
  minQuantity?: T;
  isActive?: T;
  maxUses?: T;
  maxUsesPerCustomer?: T;
  usedCount?: T;
  validFrom?: T;
  validUntil?: T;
  buyXGetYRules?:
    | T
    | {
        buyQuantity?: T;
        buyProduct?: T;
        getQuantity?: T;
        getProduct?: T;
        getDiscountPercent?: T;
        id?: T;
      };
  applicableProducts?: T;
  excludedProducts?: T;
  applicableCategories?: T;
  excludedCategories?: T;
  customerSegments?: T;
  applicableCustomerTiers?: T;
  specificCustomers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    headline?: T;
                    subheadline?: T;
                    cta?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              autoplay?: T;
              autoplayDelay?: T;
              id?: T;
              blockName?: T;
            };
        featuredCategories?:
          | T
          | {
              title?: T;
              subtitle?: T;
              categories?:
                | T
                | {
                    category?: T;
                    overrideImage?: T;
                    id?: T;
                  };
              showViewAll?: T;
              viewAllText?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        productRail?:
          | T
          | {
              title?: T;
              products?: T;
              showGenderFilter?: T;
              showViewAll?: T;
              viewAllText?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        brandStory?:
          | T
          | {
              sectionLabel?: T;
              headline?: T;
              description?: T;
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              sectionLabel?: T;
              headline?: T;
              subheadline?: T;
              placeholder?: T;
              buttonText?: T;
              mobileButtonText?: T;
              privacyText?: T;
              successHeadline?: T;
              successMessage?: T;
              trustBadges?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              testimonials?:
                | T
                | {
                    author?: T;
                    location?: T;
                    body?: T;
                    rating?: T;
                    verified?: T;
                    date?: T;
                    id?: T;
                  };
              autoplay?: T;
              autoplayDelay?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  featuredImage?: T;
  gallery?: T;
  tags?: T;
  isFeatured?: T;
  allowComments?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-tiers_select".
 */
export interface CustomerTiersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  tierLevel?: T;
  color?: T;
  isActive?: T;
  minLifetimeSpend?: T;
  minOrdersCount?: T;
  minAccountAgeDays?: T;
  discountPercent?: T;
  freeShipping?: T;
  earlyAccess?: T;
  exclusiveProducts?: T;
  birthdayBonus?:
    | T
    | {
        enabled?: T;
        discountPercent?: T;
        validDays?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards_select".
 */
export interface GiftCardsSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  initialValue?: T;
  balance?: T;
  currency?: T;
  expiresAt?: T;
  createdAt?: T;
  recipientName?: T;
  recipientEmail?: T;
  personalMessage?: T;
  sender?: T;
  transactions?:
    | T
    | {
        type?: T;
        amount?: T;
        date?: T;
        order?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts_select".
 */
export interface AbandonedCartsSelect<T extends boolean = true> {
  customer?: T;
  guestEmail?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  total?: T;
  currency?: T;
  abandonedAt?: T;
  recoveredAt?: T;
  recoveryStatus?: T;
  order?: T;
  recoveryEmailSentAt?: T;
  discountCode?: T;
  recoveryLinkToken?: T;
  ipAddress?: T;
  userAgent?: T;
  referrer?: T;
  utmData?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  storeName?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  announcement?: string | null;
  heroSlides?:
    | {
        headline?: string | null;
        subheadline?: string | null;
        cta?: string | null;
        link?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  trendingSearches?:
    | {
        term?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    instagram?: string | null;
    tiktok?: string | null;
    pinterest?: string | null;
    facebook?: string | null;
  };
  shippingPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  returnPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  defaultCurrency?: ('USD' | 'EUR' | 'GBP' | 'CAD' | 'AUD' | 'JPY' | 'INR') | null;
  enableMultiCurrency?: boolean | null;
  supportedCurrencies?:
    | {
        code: 'USD' | 'EUR' | 'GBP' | 'CAD' | 'AUD' | 'JPY' | 'INR';
        symbol: string;
        exchangeRate?: number | null;
        isDefault?: boolean | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  mainNav?:
    | {
        label?: string | null;
        link?: string | null;
        megaMenu?:
          | {
              label?: string | null;
              link?: string | null;
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        heading?: string | null;
        links?:
          | {
              label?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar".
 */
export interface TopBar {
  id: string;
  enabled?: boolean | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'tiktok' | 'facebook' | 'twitter' | 'youtube';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  offers?:
    | {
        text: string;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  showContactLink?: boolean | null;
  contactLinkText?: string | null;
  contactLinkUrl?: string | null;
  followUsText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cod-settings".
 */
export interface CodSetting {
  id: string;
  enabled?: boolean | null;
  codFee?: number | null;
  maxCodAmount?: number | null;
  minOrderAmount?: number | null;
  requireVerificationCode?: boolean | null;
  allowedPincodes?:
    | {
        pincode: string;
        areaName?: string | null;
        id?: string | null;
      }[]
    | null;
  excludedPincodes?:
    | {
        pincode: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  maxDeliveryAttempts?: number | null;
  autoCancelAfterAttempts?: boolean | null;
  chargeForReturnShipping?: boolean | null;
  codRestrictedProducts?: (string | Product)[] | null;
  codRestrictedCategories?: (string | Category)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  storeName?: T;
  logo?: T;
  favicon?: T;
  announcement?: T;
  heroSlides?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        cta?: T;
        link?: T;
        image?: T;
        id?: T;
      };
  trendingSearches?:
    | T
    | {
        term?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        pinterest?: T;
        facebook?: T;
      };
  shippingPolicy?: T;
  returnPolicy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  defaultCurrency?: T;
  enableMultiCurrency?: T;
  supportedCurrencies?:
    | T
    | {
        code?: T;
        symbol?: T;
        exchangeRate?: T;
        isDefault?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        link?: T;
        megaMenu?:
          | T
          | {
              label?: T;
              link?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  footerNav?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-bar_select".
 */
export interface TopBarSelect<T extends boolean = true> {
  enabled?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  offers?:
    | T
    | {
        text?: T;
        link?: T;
        id?: T;
      };
  showContactLink?: T;
  contactLinkText?: T;
  contactLinkUrl?: T;
  followUsText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cod-settings_select".
 */
export interface CodSettingsSelect<T extends boolean = true> {
  enabled?: T;
  codFee?: T;
  maxCodAmount?: T;
  minOrderAmount?: T;
  requireVerificationCode?: T;
  allowedPincodes?:
    | T
    | {
        pincode?: T;
        areaName?: T;
        id?: T;
      };
  excludedPincodes?:
    | T
    | {
        pincode?: T;
        reason?: T;
        id?: T;
      };
  maxDeliveryAttempts?: T;
  autoCancelAfterAttempts?: T;
  chargeForReturnShipping?: T;
  codRestrictedProducts?: T;
  codRestrictedCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}